<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Circuids.Bridge.Blazor\Circuids.Bridge.Blazor.csproj" />
    <ProjectReference Include="..\Circuids.Bridge.Shared.Sample\Circuids.Bridge.Shared.Sample.csproj" />
  </ItemGroup>

</Project>
